### ISSUE TITLE
gromacs.py error

### ISSUE THREAD

**Issue by chenxull** [NVIDIA/hpc-container-maker#204] opened 2019-12-11 11:16 UTC
I want to use gromacs.py  to generate gromacs container, but in the step 2/23 i hava meet the problem following:  
```
Step 2/23 : RUN apt-get update -y &&     DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends         python &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 87c834e52e38
Get:1 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [1019 kB]
Ign:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
Get:7 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.7 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [592 kB]
Get:11 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release [169 B]
Get:12 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release [169 B]
Get:13 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [6280 B]
Get:14 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg [169 B]
Get:15 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release.gpg [169 B]
Get:16 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages [252 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:18 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:19 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Packages [73.4 kB]
Err:19 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Packages
  Hash Sum mismatch
Get:20 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:21 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1396 kB]
Get:22 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.1 kB]
Get:23 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [996 kB]
Get:24 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [19.3 kB]
Get:25 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [7942 B]
Get:26 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [8807 B]
Fetched 16.5 MB in 1min 13s (225 kB/s)
Reading package lists...
E: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update -y &&     DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends         python &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by samcmill** [comment] 2019-12-11 14:56
@chenxull I can't reproduce this.  It might have just been a blip?

Can you please verify you have the latest version of the CUDA base image (`docker pull nvidia/cuda:10.1-devel-ubuntu16.04`) and retry?

**Comment by samcmill** [comment] 2019-12-11 14:58
FYI: https://github.com/NVIDIA/nvidia-docker/issues/571

**Comment by samcmill** [comment] 2020-01-16 17:32
Closing as what appears to have been a temporary blip.  Please reopen if it continues to occur.

**Closed by samcmill** 2020-01-16 17:32 UTC
